export { FormProfileInfoUser, FormProfileAvatar, FormProfilePassword } from './form-profile'
export { FormUpdateDish } from './form-update-dish-modal'
export { FormUpdateUserInfo } from './form-update-user-info-modal'
export { FormRegistration } from './form-registration'
export { CreateDishForm } from './create-dish-form'
