export const ROUTES = {
  HOME: '/',
  DISHES: 'home',
  DISHES_CATEGORY: ':category',
  ORDERS: 'orders',
  BILLS: 'bills',
  RESERVATION: 'reservation',
  LOGIN: 'login',
  PROFILE: 'profile',
  ADMIN_PANEL: 'admin',
  ADMIN_STATISTICS: 'statistics',
  ADMIN_STATISTICS_CATEGORY: ':statistics',
  ADMIN_RESTAURANT: 'restaurant',
  ADMIN_RESTAURANT_CATEGORY: ':restaurant',
  ADMIN_EMPLOYEES: 'employees',
  ADMIN_EMPLOYEES_CATEGORY: ':employees',
  ADMIN_SETTING: 'settings',
  DELIVERY: 'delivery',
  DELIVERY_HOME: '/delivery/home',
  DELIVERY_ORDERS: '/delivery/orders',
  DELIVERY_HISTORY: '/delivery/history',
}
