export const ROUTES = {
  HOME: '/',
  DISHES: 'home',
  DISHES_CATEGORY: ':category',
  ORDERS: 'orders',
  BILLS: 'bills',
  LOGIN: 'login',
  PROFILE: 'profile',
  ADMIN_PANEL: 'admin',
  ADMIN_STATISTICS: 'statistics',
  ADMIN_STATISTICS_CATEGORY: ':statistics',
  ADMIN_DISHES: 'dishes',
  ADMIN_EMPLOYEES: 'employees',
  ADMIN_EMPLOYEES_CATEGORY: ':employees',
  ADMIN_SETTING: 'settings',
}
