export { ReactComponent as IconMinus } from './icon-minus.svg'
export { ReactComponent as IconPlus } from './icon-plus.svg'
export { ReactComponent as IconHome } from './icon-home.svg'
export { ReactComponent as IconNote } from './icon-note.svg'
export { ReactComponent as IconClock } from './icon-clock.svg'
export { ReactComponent as IconReceipt } from './icon-receipt.svg'
export { ReactComponent as IconArrowLeft } from './icon-arrow-left.svg'
