export { SidebarLinkListSkeleton } from './sidebar-link-list-skeleton'
export { TableLineSkeleton } from './table-line-skeleton'
export { DishesListSkeleton } from './dish-card-skeleton'
export { RadioButtonCardSkeleton } from './radio-button-card-skeleton'
export { InfoDeliverySkeleton } from './info-delivery-skeleton'
export { OrderDetailsItemsSkeleton } from './order-details-items-skeleton'
export { StatisticLabelsSkeleton } from './statistic-labels-skeleton'
