export { validationPicture } from './validationSchemaPicture'
export { validationDish } from './validationSchemaDishItems'
export { validationUser } from './validationSchemaUserItems'
export { validationDelivery } from './validationSchemaDeliveryItems'
export { phoneNumber } from './validationPhoneNumber'
