export { formatString } from './formatString'
export { ORDER_TOGGLE_MENU_VALUES } from './constants'
export { correctionName } from './correctionName'
export { firstLetterUpperCase } from './firstLetterUpperCase'
export { spacesBetweenCapitalsLetters } from './spacesBetweenCapitalsLetters'
export { convertOrderData } from './convertOrderData'
export { default as FadeIn } from './FadeIn'
export { generateArray } from './generateArray'
export { withProps } from './withProps'

export { validationUser, validationDish, validationPicture } from './validationSchemaItems'
