export {
  IconMinus,
  IconPlus,
  IconUser,
  IconOval,
  IconDelivery,
  IconCash,
  IconMasterCard,
  IconVisa,
  IconAddTipAmount,
  IconEmail,
  IconSearch,
  IconMore,
  IconDineIn,
  IconAway,
  IconHome,
  IconNote,
  IconClock,
  IconReceipt,
  IconArrowLeft,
  TestIcon,
  IconPrinter,
  IconIndicator,
  IconDelete,
} from './icons'
export { LogoCocaImg, LogoCocaText } from './logo-type'
