export {
  IconMinus,
  IconPlus,
  IconUser,
  IconOval,
  IconAwayIndicator,
  IconDineInIndicator,
  IconDelivery,
  IconCash,
  IconMasterCard,
  IconVisa,
  IconAddTipAmount,
  IconEmail,
  IconSearch,
  IconMore,
  IconDineIn,
  IconAway,
  IconDeliveryIndicator,
} from './icons'
