#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


BRed='\033[1;31m'
BCyan='\033[1;36m'
BBlue='\033[1;34m'
BPurple='\033[1;35m'
BWhite='\033[1;37m'
NC='\033[0m' # No Color

echo " "
echo "------------------------------------------------------------------------------------------------"
printf "    😈 ${BWhite}I'm checking your code - be AFRAID and TREMBLE!!!${NC} 😈\n"
echo "------------------------------------------------------------------------------------------------"
echo " "

printf "${BWhite} - Check ${BBlue}TypeScript${NC} ${BWhite}standards${NC}"
npm run types ||
(  echo " "
   echo "------------------------------------------------------------------------------------------------"
   printf "   😥 ${BRed}!!! ${BWhite}Failed${NC} ${BBlue}TypeScript${NC} ${BWhite}check. Are you seriously trying to push that SHIT??!!${NC} 🤬\n";
   echo "------------------------------------------------------------------------------------------------"
   echo " "
   false;
)

printf "${BWhite} - Check ${BPurple}ESLint${NC} ${BWhite}standards${NC}"
npm run lint ||
(  echo " "
   echo "------------------------------------------------------------------------------------------------"
   printf "   😥 ${BRed}!!! ${BWhite}Failed ${BPurple}ESLint ${BWhite}check. Are you seriously trying to push that SHIT??!!${NC} 🤬\n";
   echo "------------------------------------------------------------------------------------------------"
   echo " "
   false;
)

# If it OK you can pull
echo " "
echo "------------------------------------------------------------------------------------------------"
printf "    🚀🚀 ${BWhite}It looks good! You're a fucking ${BCyan}ROCKET!!!${NC} 🚀🚀\n";
echo "------------------------------------------------------------------------------------------------"
echo " "
